# Generated by Django 4.1.5 on 2023-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_alter_blog_body_blog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='blog',
            name='content_live',
            field=models.BooleanField(default=False),
        ),
    ]
