# Generated by Django 4.1.5 on 2023-02-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255)),
                ('sub_email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'New Letter Subscribers',
            },
        ),
    ]
