# Generated by Django 4.1.5 on 2023-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options_blog_views_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='mtag_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='mtag_keywords',
            field=models.TextField(blank=True),
        ),
    ]
