# Generated by Django 4.1.5 on 2023-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_mtag_description_tag_mtag_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('keyWords', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Tag Info',
                'verbose_name_plural': 'Home Tags',
                'ordering': ['-created_at'],
            },
        ),
    ]
